services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
#      target: production
    image: pavesadmin/intranet-pms:latest
    container_name: project-management
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - app-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

volumes:
  app-logs:
    driver: local